# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'rubocop', require: false
gem 'colorize', require: true
gem "ruby2d", "~> 0.12.1", require: true
gem 'artii', require: true